- src/configuration.c
Fix Doxygen warnings, and make configuration function parameters consistent.
> Minor configuration code clean-up.

- CODE_OF_CONDUCT.md
Do not use the public mptcp@lists.01.org mailing list for handling of Code of Conduct related reports.  Use the private mptcp-owner@lists.01.org instead.
> CODE_OF_CONDUCT: Use private e-mail for reporting.

- README.md
* Add note about CAP_NET_ADMIN requirement.
* Mention running ldconfig as an alternative to setting the
LD_LIBRARY_PATH environment variable.
* Minor wording updates.
> README: Clarify mptcpd execution instructions.

- tests/test-path-manager.c
- tests/test-plugin.h
Building mptcpd with [clang](http://clang.llvm.org/) resulted in link- and compile-time errors in the `mptcpd/tests` directory.  This set of changes address those errors.  Fixes #7.
> Fix errors under clang build.

- README.md
The mptcpd `configure` script requires [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/) to be installed.  Add it to the list of basic build dependencies.
> README: Add missing note about pkg-config dep.

- .clang-format
The RawStringFormats configuration value changed in structure after
version 6 of clang-format. Since the values were defaults, removing the
block from .clang-format keeps the same behavior but maintains
compatibility with various tool versions.
> Make clang-format configuration compatible with versions after 6.0.0

- Makefile.am
- README.md
- configure.ac
- include/mptcpd/plugin.h
- tests/Makefile.am
- tests/call_count.c
- tests/call_plugin.c
- tests/mptcpd_addr.c
- tests/plugin_four.c
- tests/plugin_one.c
- tests/plugin_three.c
- tests/plugin_two.c
- tests/test-commands.c
- tests/test-plugin.h
Some areas of code in **mptcpd** were not reflected in code coverage results.  Improve the code coverage results by adding **mptcpd** library function calls to the unit test suite, as well as removing the "`-O2`" compiler optimization flag that interfered with the code coverage.
> Improve code coverage.

- lib/path_manager.c
- plugins/path_managers/sspi.c
- src/path_manager.c
Some MPTCP generic netlink message and command payloads were not correctly or fully migrated to the new API in PR #15.  Update those that were missed.
> Correct genl API attribute mismatches.

- src/mptcp.service.in
The multipath-tcp.org kernel's "netlink" path manager requires
processes that invoke commands over its generic netlink API to have
the CAP_NET_ADMIN capability.  However, the mptcpd mptcp.service file
doesn't explicitly grant that capability since it runs mptcpd under an
unprivileged dynamically created user (DynamicUser=yes), resulting in
mptcpd being in incapable of successfully issuing path management
commands to the kernel.
Add "AmbientCapabilities=CAP_NET_ADMIN" to grant mptcpd the necessary
capability when starting it through systemd.  Fixes #28.
> src: Explicitly grant CAP_NET_ADMIN capability.

- lib/network_monitor.c
The network monitor code that removes a network address from
monitoring had a function parameter mismatch that was hidden a pointer
to void.  Correct the mismatch, and make all network monitor functions
that support the RTM_NEWADDR, RTM_DELADDR, and RTM_GETADDR rtnetlink
messages consistently use the same (internal) network address
information encapsulation type.  Fixes #27.
> lib: Fix abort on monitored net address removal.

- lib/network_monitor.c
Tracked addresses to be removed due to a `RTM_DELADDR` rtnetlink event were needlessly re-inserted into the address queue prior to removal.   Refactor rtnetlink `RTM_NEWADDR` and `RTM_DELADDR` event `IFA_ADDRESS` attribute iteration to simplify handling of new, updated, and removed addresses.
> network_monitor: Do not track removed address.

- src/path_manager.c
Dereferencing of NULL pointers could potentially occur when handling
MPTCP generic netlink API events with optional payload attributes.
Prevent such dereferencing from occurring by adding the appropriate
NULL pointer check.
An existing NULL pointer check that verifies that a required subflow
backup priority flag was retrieved was also corrected.
These changes address errors flagged in a static analysis build.
> src: Fix potential NULL pointer dereferencing.

- Makefile.am
- NEWS
- README.md
- configure.ac
* This Multipath TCP Daemon alpha release replaces support for the deprecated MPTCP generic netlink API with the one found in the multipath-tcp.org 0.95+ kernel (see multipath-tcp/mptcp@4ea5dee), and has been verified to work with that kernel.
* Several actual and potential memory access violations were fixed in the `mptcpd` network monitor, path manager, and "`sspi`" plugin.
* The `mptcp.service` systemd service file now correctly grants the necessary privilege (`CAP_NET_ADMIN`) for proper operation of the `mptcpd` program.
> mptcpd 0.2a: Alpha release

- configure.ac
- tests/Makefile.am
This optimization flag (in gcc 4.8 and later) is gdb-friendly and satisfies optimizer requirements for _FORTIFY_SOURCE.
> Use -Og for debugger-friendly optimization

- include/mptcpd/path_manager.h
- lib/path_manager.c
- src/path_manager.c
- tests/test-commands.c
- tests/test-path-manager.c
The ELL generic netlink API was changed in a non-backward compatible way in the upcoming 0.21 release.  Update mptcpd to use new ELL generic netlink API.
The update slightly modifies behavior so that a l_genl_family object  used for interactions with the kernel cannot be allocated until the  generic netlink family, "`mptcp`" is this case, appears.  This isn't a  major change, but it will affect some of the mptcpd tests.
> Transition to new ELL genl API.

- include/mptcpd/path_manager_private.h
- src/path_manager.c
Only one multicast group, "mptcp_events", in the generic netlink
"mptcp" family is used by mptcpd.  There is no need to track multiple
group IDs.  Drop the multicast group ID array, and replace it with
single scalar variable.
> path_manager: Only track one genl multicast group.

- src/path_manager.c
- tests/test-commands.c
- tests/test-path-manager.c
With the new ELL generic netlink API, it is no longer enough to simply
set a watch for the "mptcp" generic netlink family since the watch is
only triggered on a family change (appeared or vanished).  If the
family already existed prior to mptcpd start the watch won't be
triggered.  Explicitly request the "mptcp" family, and only bother
setting a watch if that request failed.  Fixes a problem where the
mptcpd would not fully initialize it's path manager bridge component.
> path_manager: Explicitly request "mptcp" family.

- src/configuration.c
- tests/test-configuration.c
Providing `mptcpd` with multiple string typed configuration parameters,  i.e. more than one plugin directory or more than one path manager name, through the command line or a combination of the command line with the `mptcpd` configuration file, causes a memory leak in `mptcpd_config`.  This is caused by failing to deallocate the strings in `mptcpd_config` before resetting their values.  Deallocate those strings before resetting.
> configuration: Fix memory leaks.

- configure.ac
- include/mptcpd/path_manager_private.h
- src/path_manager.c
Issue a warning if the [multipath-tcp.org](https://multipath-tcp.org/) kernel is not [configured](http://multipath-tcp.org/pmwiki.php/Users/ConfigureMPTCP) at run-time in a manner suitable for mptcpd.  See #36 for further discussion.
> src: Warn on incorrect run-time kernel config.

- configure.ac
ELL's new genl API, which mptcpd requires, was made available in ELL
0.21.  Update the corresponding configure script check accordingly.
> configure: Require ELL >= 0.21.

- lib/network_monitor.c
- src/path_manager.c
Fix minor issues flagged by the [clang-tidy](https://clang.llvm.org/extra/clang-tidy/) tool, such as bug prone casts, and missing parenthesis around macro arguments.
> Correct issues flagged by clang-tidy.

- include/mptcpd/Makefile.am
- include/mptcpd/path_manager_private.h
- include/mptcpd/plugin.h
- include/mptcpd/plugin_private.h
- lib/plugin.c
- src/path_manager.c
- tests/call_plugin.c
- tests/test-cxx-build.cpp
- tests/test-plugin.c
The `libmptcpd` library exposes an API that is meant solely for use by the `mptcpd` program, not plugins.  Move functions in the private plugin API to a new `<mptcpd/plugin_private.h>` header that doesn't get installed.
> Move private plugin API to a separate file.

- .gitignore
- configure.ac
- lib/Makefile.am
- lib/mptcpd.pc.in
Generate a `mptcpd.pc' pkg-config file that may be used by mptcpd
plugin developers to obtain the necessary mptcpd build related
information.
> Add pkg-config support.

- lib/network_monitor.c
- src/path_manager.c
Fix a memory leak that occurred when destroying a network monitor
instance that hasn't been fully initialized.  In particular, do not
attempt to retrieve network addresses if network interfaces are not
being tracked by the mptcpd network monitor.
The memory leak was caused by an incomplete attempt to retrieve
network addresses during mptcpd network monitor destruction.  Network
address retrieval is not necessary during mptcpd network monitor
destruction, but is unnecessarily triggered because of an ELL related
workaround that forces network address retrieval through the rtnetlink
API to occur only after network interface retrieval completes by
leveraging the netlink command "destroy" function as the trigger for
address retrieval.
Fixes #17.
> network_monitor: Fix netlink related memory leak.

- configure.ac
- m4/mptcpd_flags.m4
Support the GCC / Clang address, leak, and undefined behavior [sanitizers](https://github.com/google/sanitizers).  Closes #10.
> Support various sanitizers

- include/mptcpd/types.h
- lib/plugin.c
- plugins/path_managers/sspi.c
- src/path_manager.c
Logging the MPTCP connection token is security risk.  Remove all such log messages.
Fixes #25.
> Do not log MPTCP connection token.

- NEWS
- README-alpha
- README.md
- configure.ac
- lib/mptcpd.pc.in
This is the Multipath TCP Daemon beta release.
- All known memory leaks have been fixed.
- A potential security hole related to logging of MPTCP connection
tokens was closed.  Logging of MPTCP connection tokens no longer
occurs.
- Support for compiler-based address, leak, and undefined behavior sanitizers is now available, and may be enabled through corresponding `configure` script options.  Run `./configure --help`  for the full list of options.
- Diagnostic messages will be issued if the Linux kernel is not properly configured to support a user space MPTCP path manager like mptcpd.
- Documentation on how to contribute to mptcpd is available in the [`CONTRIBUTING.md`](https://github.com/intel/mptcpd/blob/master/CONTRIBUTING.md) file.
- A `pkg-config` …
> mptcpd 0.3: Beta release

- tests/test-plugin.c
The mptcpd plugin unit test created a temporary test directory but did
not remove it.  Remove that directory as soon as it is no longer
needed.
> tests: Clean up temporary plugin test directory.

- configure.ac
- lib/mptcpd.pc.in
Automatically update the minimum required version of ELL in the
`mptcpd.pc' pkg-config file to match the version in the configure
script to avoid potential mismatches.
> Automatically update ELL version in `mptcpd.pc'.

- lib/plugin.c
- tests/Makefile.am
- tests/test-plugin.c
While not initially intended, the mptcpd plugin framework allows an instance of `mptcpd_plugin_ops` with `NULL` callback fields to be registered.  However, the plugin framework did not check if the callback was `NULL` prior to calling.  Add the appropriate `NULL` check prior to invoking the plugin callback to prevent a seg fault from occurring.  This also allows the user to avoid having to implement stubs for unused plugin operations.  Fixes #65.
> lib: Verify plugin op is non-NULL before calling.

- NEWS
- include/mptcpd/path_manager.h
- include/mptcpd/plugin.h
- lib/path_manager.c
- tests/test-commands.c
Support for sending the `REMOVE_ADDR` MPTCP option through the `MPTCP_CMD_REMOVE` generic netlink command was missing.  Add a new `mptcp_pm_remove_addr()` function that provides this functionality to allow mptcpd path manager plugins to stop advertising specific addresses.
> Add missing support for REMOVE_ADDR.

- plugins/path_managers/Makefile.am
- tests/Makefile.am
VPATH builds exhibited a compile-time error regarding a missing
<mptcpd/config-private.h> header.  That header ends up being placed
under include/mptcpd in the build directory, not the top level source
directory. Explicitly add the build directory to the include path so
that VPATH based builds succeed.  Fixes #63.
> Add build dir to include path.

- configure.ac
- tests/Makefile.am
To properly support gcc's _FORTIFY_SOURCE feature some optimization
level above zero (i.e., "-O0") is required.  Mptcpd explicitly adds
the "-Og" flag when debugging is enabled, but that flag was being
overridden for the mptcpd C++ build test, `test-cxx-build', due to the
way it was appended to the C++ compiler flags variable, CXXFLAGS.
CXXFLAGS ended up containing "-Og -g -O0".  The trailing optimization
flag "-O0" superceded the earlier "-Og" flag, which ultimately caused
optimization to be disabled entirely.  That triggered a preprocessor
warning on some platforms:
/usr/include/features.h:397:4: warning: #warning _FORTIFY_SOURCE
requires compiling with optimization (-O) [-Wcpp]
Append the "-Og" flag to CXXFLAGS in the `configure' script rather
than the Makefile to work around the …
> Correct C++ debug optimization flag order.

- configure.ac
Favor the Autoconf Archive AX_APPEND_COMPILE_FLAGS and
AX_APPEND_LINK_FLAGS macros over the mptcpd-specific counterparts
MPTCPD_ADD_COMPILE_FLAG and MPTCPD_ADD_LINK_FLAG, respectively.  The
the Autoconf Archive macros have the advantage of allowing multiple
flags to be checked in a single macro call, as well as not assuming
that a specific language (e.g. C) is being used.
MPTCPD_ADD_{COMPILE,LINK}_FLAG will be left in place for now since
they allow an action to be executed on flag check failure.
> configure: Simplify compile and link flag checks.

- tests/lib/test-plugin.h
Replace IP addresses used in the mptcpd units tests with those that
fall into an address range specifically reserved for documentation
purposes by the IETF.  In particular, mptcpd test IPv4 and IPv6
addresses now conform to [RFC 5737](https://tools.ietf.org/html/rfc5737) and [RFC 3849](https://tools.ietf.org/html/rfc3849), respectively.  The
goal is to avoid potentially advertising routable addresses through
MPTCP.
> tests: Use IP addresses reserved for documentation

- configure.ac
Versions of ELL greater than 0.33 drop the ELL plugin API.  Until
the mptcpd plugin framework has an alternative underlying
implementation in place, restrict the version of ELL supported by
mptcpd to be between 0.27 and 0.33.  The minimum version was an
existing restriction.
> configure: Restrict ELL to [0.27, 0.33] range.

- tests/test-cxx-build.cpp
The mptcpd test-cxx-build unit test fails to compile with recent
versions of ELL (e.g., 0.33) due to an assignment of a void* to a
uint8_t* without a cast in the inline l_secure_memcmp() function in
<ell/util.h>.  Drop the <ell/util.h> include from tests-cxx-build.cpp
to address the C++ build problem since it is no longer needed.
> tests: Workaround C++ error in <ell/util.h>.

- include/mptcpd/id_manager.h
- include/mptcpd/path_manager.h
- include/mptcpd/path_manager_private.h
- lib/path_manager.c
- plugins/path_managers/addr_adv.c
- src/path_manager.c
Add a "global" MPTCP address ID manager instance to mitigate potential duplicate MPTCP address IDs between plugins, as well as to make it easier to detect and handle changes in the kernel's own address ID state in the future. Plugins may access the gobal MPTCP address ID manager through the new `mptcpd_pm_get_idm()` function.
Fixes #88.
> Add a global address ID manager

- NEWS
- configure.ac
- include/mptcpd/plugin.h
- include/mptcpd/plugin_private.h
- lib/mptcpd.pc.in
- lib/plugin.c
- plugins/path_managers/addr_adv.c
- plugins/path_managers/sspi.c
- src/path_manager.c
- tests/plugins/noop/noop.c
- tests/plugins/priority/one.c
- tests/plugins/priority/two.c
- tests/plugins/security/four.c
- tests/plugins/security/three.c
- tests/test-cxx-build.cpp
- tests/test-plugin.c
ELL dropped its plugin API after release 0.33.  Revise the mptcpd plugin framework to instead use the standard `dlopen()` / `dlsym()` / `dlclose()` family of functions.  Take the opportunity to pass a pointer to the `struct mptcpd` object to the plugin `init` and `exit` functions so that plugins may have earlier and later, respectively, opportunities to perform calls through the mptcpd main path manager interface.  Fixes #84.
> Update plugin framework to not depend on ELL

- include/mptcpd/Makefile.am
- include/mptcpd/id_manager_private.h
- lib/id_manager.c
- src/path_manager.c
- tests/test-id-manager.c
It is possible that some MPTCP address IDs may have been associated with local IP addresses prior to mptcpd start, e.g. through previous runs of mptcpd or other non-mptcpd initiated calls to the netlink path manager.  Synchronize the address IDs maintained by mptcpd with those in the kernel. 
Fixes #91.
> Synchronize ID manager with kernel state

- include/mptcpd/path_manager.h
- include/mptcpd/path_manager_private.h
- include/mptcpd/types.h
- lib/path_manager.c
- src/commands_upstream.c
- tests/test-commands.c
There is no need for a `mptcpd_addr_info` array length argument in the  `dump_addrs` callback since the kernel sends multiple replies containing a single dumped `addr`, rather than a single reply with multiple dumped `addrs`.
> Drop addr_info length from mptcpd_pm_dump_addrs().

- include/mptcpd/path_manager_private.h
- src/path_manager.c
Defer plugin load until after the generic netlink family for the
netlink path manager is ready for use since the recent plugin
framework updates make it possible for path management related calls
to be invoked during plugin initialization.  This also effectively
ensures that the mptcpd path manager bridge is always ready, obviating
the need to poll for readiness by plugins.
> src: Load plugins after netlink PM is available

- NEWS
- plugins/path_managers/sspi.c
The reverse lookup of a network interface index from an IP address
failed due to passing the address of a pointer to a sockaddr to the
lookup function rather than the pointer itself.
> sspi: Fix network interface index/addr lookup.

- lib/network_monitor.c
- lib/plugin.c
- src/netlink_pm_mptcp_org.c
ELL 0.39 moved the likely() and unlikely() macros to a new
<ell/useful.h> header.  Rather than conditionally include that header
for ELL >= 0.39 just drop use of those macros in mptcpd.  They didn't
provide a performance benefit in the areas of mptcpd in which they
were used so don't bother using them.
> Drop use of ELL likely()/unlikely() macros.

- lib/network_monitor.c
Free internal data allocated by mptcpd on failure of network monitor
operations registration.  Such a failure should never occur but better
safe than sorry.
> lib: Fix potential memory leak in network monitor.

- configure.ac
Update bug report address to "mptcp@lists.linux.dev".  The previous
"mptcp@lists.01.org" mailing list will no longer be used.
> configure: Update bug report address.

- configure.ac
Use the mptcpd GitHub URL "https://github.com/intel/mptcpd" instead of
the less used 01.org URL "https://01.org/multipath-tcp-linux".
> configure: Update package URL.

- src/netlink_pm_upstream.c
The get_limits PM command implementation incorrectly attempted to
perform a genl "dump" operation rather than the expect "doit".  Send
the command message via l_genl_family_send() instead of
l_genl_family_dump().  This corrects an ENOTSUP error issued by the
kernel when attempting to perform the MPTCP_PM_CMD_GET_LIMITS
command.
> src: Fix ENOTSUP error for get_limits command.

- src/commands.h
- src/netlink_pm_mptcp_org.c
- src/netlink_pm_upstream.c
The generic netlink message payload size calculation for the upstream kernel `add_addr` command incorrectly used the size of the type used to hold the size of the `addr`, e.g. equivalent to `sizeof(size_t)`, instead of the actual size of the `addr`, `sizeof(struct in_addr)` or `sizeof(struct in6_addr)`.  The incorrect payload size calculation would only be obvious when using an IPv6 address.
> Correct genl msg payload size calculation.

- include/mptcpd/path_manager.h
- include/mptcpd/private/path_manager.h
The upstream kernel's path management API exposes two types of path management commands, those more suited to servers and those more suited to clients (still a work-in-progress). Clarify documentation of server-oriented and client-oriented path managements command functions in libmptcpd.
Fixes #115.
> include: Clarify server- vs client-oriented.

- NEWS
- configure.ac
- include/mptcpd/path_manager.h
- MPTCP path management generic netlink events recently added to the
upstream Linux kernel are now supported, and propagated to mptcpd
plugins.  The same API is also found in the multipath-tcp.org
kernel.  Differences between the two kernels are transparent to
mptcpd plugins.
- Mptcpd now supports the upstream Linux kernel server-oriented
MPTCP_PM_CMD_SET_FLAGS generic netlink command through the new
mptcpd_pm_set_flags() function.  It allows the user to set MPTCP
flags for a specific local IP address.
- An incorrect buffer size calculation when calling
mptcpd_pm_add_addr() when using an IPv6 addresses on platforms
running the upstream Linux kernel was corrected.
- An "operation not supported" error that occurred when attempting to
retrieve MPTCP resource limits through the …
> mptcpd 0.7

- configure.ac
Enabling -DFORTIFY_SOURCE=* and -fstack-protector-* by default may
overwrite global (build) system settings, causing redefinition errors at
compile time.
Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>
> configure: add --disable-stack-protection option

- .github/workflows/ccpp.yml
Make sure all package dependencies are installed non-interactively.
Also, use apt-get instead of apt since the apt command line interface
is not stable.
> Install automated build deps non-interactively.

- .github/workflows/ccpp.yml
The Linux kernel in Ubuntu 20.04 doesn't support MPTCP, which causes
some mptcpd tests to fail.  Explicitly declare those as tests expected
to fail through the XFAIL_TESTS make variable when running `make
check' and `make distcheck'.  This addresses the GitHub Action build
workflow on Ubuntu 20.04.
> cccp.yml: Expect tests to fail on Ubuntu 20.04.

- configure.ac
- lib/id_manager.c
- src/commands.c
Work around missing ELL functions used by mptcpd that were introduced in ELL 0.31+.
Check if the `l_genl_msg_get_extended_error()` function is available.   It was introduced in ELL 0.31.  Set the extended error message to `NULL`  if the function is not available.
The mptcpd ID manager uses the ELL `l_hashmap_replace()` function, but that function was introduced in ELL 0.33.  Implement the `l_hashmap_replace()` functionality in mptcpd through calls to `l_hashmap_remove()` and `l_hashmap_insert()` when `l_hashmap_replace()` is not available.
> Fix build regression against ELL 0.31.

- include/linux/mptcp_org.h
- include/mptcpd/path_manager.h
- lib/path_manager.c
- src/netlink_pm_mptcp_org.c
The remote address and port are required when creating a subflow.  Update the `mptcpd_pm_add_subflow()` implementation accordingly.
Fixes #134.
> Require remote address for subflow creation.

- src/mptcpize.c
The gcc 11.1 static analyzer flagged a potential NULL argument passed
to a strlen() call.  Check for NULL prior to calling strlen().
> mptcpize: Fix gcc static analyzer diagnostic.

- .github/workflows/ccpp.yml
Some tests that were listed as expected to fail through the Automake `XFAIL_TESTS` variable now pass, triggering an unexpected pass "`XPASS`" test suite failure.  Remove the tests that now pass from `XFAIL_TESTS`.
> ccpp.yml: Remove tests that pass from XFAIL list.

- src/Makefile.am
- src/configuration.c
the plugin dirname is $(libdir)/mptcpd/ on standard configurations:
use this value in case the value of plugin_dir is empty in
/etc/mptcpd/mptcpd.conf.
Signed-off-by: Davide Caratti <dcaratti@redhat.com>
> allow empty values of "plugin_dir" in mptcpd.conf. (#144)

- src/configuration.c
Overriding a given system configuration (e.g. /etc/mptcpd.conf) value
through the corresponding command line option could fail if the system
configuration parse fails.  Parse the command line options before the
system configuration to prevent such a problem from occurring.
> src: Fix configuration order issues.

- include/linux/mptcp_upstream.h
Update mptcpd's copy of the upstream kernel's <linux/mptcp.h> user API
header to the latest version.  It adds reset reason codes.
> include: Update <linux/mptcp_upstream.h>.

- .gitignore
- man/Makefile.am
- man/mptcpize.8.in
- src/mptcpize.c
Add a new mptcpize.8 man page, and clean up help message output from the mptcpize command itself.
> Improve mptcpize documentation

- include/mptcpd/path_manager.h
- include/mptcpd/private/netlink_pm.h
- include/mptcpd/private/path_manager.h
- lib/path_manager.c
- plugins/path_managers/addr_adv.c
- plugins/path_managers/sspi.c
- src/netlink_pm_mptcp_org.c
- src/netlink_pm_upstream.c
- src/path_manager.c
- tests/test-commands.c
There should be no overlap between the user space (client-oriented) and in-kernel (server-oriented) variants of the `ADD_ADDR` and `REMOVE_ADDR` related command implementation in mptcpd.  They have different use cases, and the previously forced overlap of the APIs in mptcpd was a source of confusion.  Split the operations specific to the in-kernel path manager to a new `mptcpd_kpm` code namespace to make the difference explicit and more obvious.
> Split in-kernel PM add_addr/remove_addr commands.

- AUTHORS
- COPYING
- NEWS
- configure.ac
- The mptcpd library API now splits path management operations specific to the in-kernel path manager found in the upstream Linux kernel into a separate "`mptcpd_kpm`" API namespace to differentiate `ADD_ADDR` and `REMOVE_ADDR` related operations between the in-kernel and user space cases.  The operations for the two are different and have different use cases.
- Two new mptcpd command line arguments were added: "`--addr-flags`" and "`--notify-flags`", along with the equivalent settings in the mptcpd system configuration file (e.g., `/etc/mptcpd/mptcpd.conf`).  "`addr-flags`" are used when announcing an IP address.  Similar flags are used by the "`ip mptcp`" sub-command.  See the [ip-mptcp(8)](https://man7.org/linux/man-pages/man8/ip-mptcp.8.html) and man page for further details on these …
> mptcpd 0.8

- .github/workflows/coverage.yml
Coveralls isn't showing the source code if the user isn't logged in.
Attempt to work around the issue by setting source paths.
> github: Attempt to work around Coveralls issue.

- src/commands.c
- src/commands.h
- src/netlink_pm_mptcp_org.c
- src/netlink_pm_upstream.c
A port may be specified as an attribute of the upstream kernel
`MPTCP_PM_CMD_ADD_ADDR` command.  Append it to generic netlink message
accordingly.  Make sure the `MPTCP_PM_ADDR_FLAG_SIGNAL` flag is also set
since the kernel won't use the port without it.
> src: Append port to add_addr command if given.

- include/mptcpd/path_manager.h
- include/mptcpd/private/netlink_pm.h
- include/mptcpd/private/path_manager.h
- include/mptcpd/types.h
- lib/path_manager.c
- src/netlink_pm_upstream.c
- src/path_manager.c
- tests/test-commands.c
Mptcpd synchronizes its internal state with the kernel at process start, and then continues with initialization such as plugin load and trigger the "pm_ready" callback.  However, the kernel sync operation completes asynchronously meaning the kernel isn't actually "ready" when the plugins are loaded and "pm_ready" callback is triggered.
Introduce a new "`complete`" function parameter to mptcpd path manager command functions that complete asynchronously, e.g. `dump_addrs`, that is called when the operation completes.   The "`complete`" function differs from user provided callbacks that are called when asynchronous results are available in that it is called regardless of whether or not asynchronous results are available.  Furthermore, they are only called once at the very end of the …
> Correct mptcpd internal initialization order issues.

- .github/workflows/ccpp.yml
- .github/workflows/coverage.yml
- include/mptcpd/types.h
- lib/network_monitor.c
- man/mptcpd.8.in
- src/configuration.c
this change-set implement the functionality discussed in recent public meetings.
Depending on a newly introduced configuration flag, new address are used/notified only if a default route is available for such address/interface.
There are a few quirks due to ipv4 route resolution and libell async notification, see the 3rd patch for the details. 
This should close issue #170
> implement new address filter based on default route availability

- README.md
- configure.ac
The new default route availability based address filter introduced in
PR #179 requires features in ELL >= 0.30.  Adjust the ELL version
check and documentation accordingly.
> Increase required version ELL to 0.30.

- lib/network_monitor.c
- plugins/path_managers/sspi.c
- tests/lib/sockaddr.c
TODO comments regarding suitability of memcmp() for IPv6 address
comparisons are not needed since the uninitialized byte concerns
expressed in the comments are incorrect.
> Remove obsolete TODO comments.

- lib/network_monitor.c
The private `mptcpd_addr_info` structure in `lib/network_monitor.c` has the same name as the one in the public mptcpd API declared in `<mptcpd/addr_info.h>`.  Rename the private one to `nm_addr_info` to avoid confusion and potential namespace conflicts in the future.
Also make the new route check code more closely match the mptcpd coding style.
> lib: Correct conflicting _addr_info struct names. 

- configure.ac
Autoconf 2.71 deprecates the AC_PROG_CC_STDC macro.  Use AC_PROG_CC
instead.
> configure: Replace obsolete AC_PROG_CC_STDC macro.

- lib/plugin.c
- man/mptcpd.8.in
- src/configuration.c
- tests/test-plugin.c
Fixed a memory leak inserted with the load-plugins options, where the `plugins_to_load` queue of the `sys_config` variable was not being destroyed on the `mptcpd_config_create` function.
Added a missing `const` qualifier to the input argument `plugins` of the `set_plugins_to_load` function.
Removed an extra space and dot on the man page.
> Load-plugins related issues fixes

- .gitignore
- include/mptcpd/Makefile.am
- include/mptcpd/addr_info.h
- include/mptcpd/private/addr_info.h
- lib/Makefile.am
- lib/addr_info.c
- src/netlink_pm_upstream.c
- src/path_manager.c
- tests/Makefile.am
- tests/test-addr-info.c
- tests/test-commands.c
Make `struct mptcpd_addr_info` opaque, and add accessor functions for the fields in that structure.  This is consistent with other opaque structures in mptcpd.
> Make struct mptcpd_addr_info opaque.

- .github/workflows/coverage.yml
The mptcpd code coverage GitHub workflow does not need the pandoc
package dependency.  Pandoc is only needed when running a `make dist'
or `make distcheck', neither of which is executed in the code coverage
workflow.
> github: Drop unnecessary pandoc dependency.

- tests/test-start-stop
Test mptcpd start and stop when MPTCP is both disabled and enabled.
> tests: Expand mptcpd start/stop test.

- .github/workflows/ccpp.yml
Leverage a GitHub workflow matrix to run debug and non-debug mptcpd
builds using the same set of steps.
> github: Run debug and non-debug mptcpd builds.

- tests/lib/call_plugin.c
- tests/plugins/priority/one.c
- tests/plugins/priority/two.c
- tests/plugins/security/four.c
- tests/plugins/security/three.c
- tests/test-addr-info.c
- tests/test-commands.c
- tests/test-configuration.c
- tests/test-cxx-build.cpp
- tests/test-id-manager.c
- tests/test-network-monitor.c
- tests/test-path-manager.c
- tests/test-plugin.c
- tests/test-sockaddr.c
Override the NDEBUG definition in <mptcpd/private/config.h> in
the mptcpd unit tests by moving the #undef NDEBUG and <assert.h>
include directives after all mptcpd includes to prevent the
assert() calls in those tests from being no-ops when building
mptcpd with debugging disabled.
This change set also addresses unused argument errors in
`tests/test-commands.c'.
> tests: Override NDEBUG for tests.

- configure.ac
Choose the default mptcpd plugin based on the kernel mptcpd is
configured to support.  Specifically, the addr_adv plugin will
continue to be the default for the upstream kernel, and the sspi
plugin will be the default for the multipath-tcp.org kernel.  The
MPTCP path management generic netlink API used by addr_adv is not
supported by the multipath-tcp.org kernel, meaning the addr_adv plugin
is not a suitable default for it.
> configure: Automatically choose default plugin.

- configure.ac
- src/Makefile.am
- src/mptcp.service.in
Recent attempts to package mptcpd for Debian triggered several [Lintian](https://lintian.debian.org/) issues.  This set of changes addresses some of them.  The list of mptcpd related Lintian warnings and errors may be found [here](https://paste.opendev.org/show/812263/).
> Fix issues flagged by Lintian.

- tests/lib/test-util.c
- tests/lib/test-util.h
- tests/test-commands.c
- tests/test-mptcpwrap
- tests/test-path-manager.c
The mptcpd unit tests test-commands, test-path-manager and test-mptcpwrap require a MPTCP capable kernel to run.  Make those tests return with an exit status (77) that causes the Automake test driver script, i.e. `test-driver' to treat the tests as skipped.  This allows the test suite to succeed when MPTCP is not available in the kernel.
The test summary from a `make check' run would look similar to the following when run on a non-MPTCP capable kernel:
```
...
PASS: test-network-monitor
SKIP: test-path-manager
SKIP: test-commands
PASS: test-configuration
...
SKIP: test-mptcpwrap
============================================================================
Testsuite summary for mptcpd 0.9
============================================================================ …
```
> Skip some tests on non-MPTCP kernels.

- tests/lib/test-util.c
- tests/lib/test-util.h
- tests/test-commands.c
- tests/test-mptcpwrap
- tests/test-path-manager.c
- tests/test-start-stop
I had to add two commits on top of #215.
I'm adding them in this new PR as I cannot edit @ossama-othman 's one, I hope that's OK :)
In short, start-stop was not working with a non-MPTCP kernel and a 'Non-interactive sudo capable'.
While at it, I also skip the test instead of doing nothing is we don't have a 'Non-interactive sudo capable'.
Now all tests are OK on my test VM:
```
PASS: test-plugin
PASS: test-network-monitor
SKIP: test-path-manager
SKIP: test-commands
PASS: test-configuration
PASS: test-id-manager
PASS: test-sockaddr
PASS: test-addr-info
PASS: test-cxx-build
PASS: test-bad-log-empty
PASS: test-bad-log-long
PASS: test-bad-log-short
PASS: test-bad-option
PASS: test-bad-path-manager
PASS: test-bad-plugin-dir
SKIP: test-start-stop
SKIP: test-mptcpwrap …
```
> Skip some tests on non-MPTCP kernels, part 2.

- Doxyfile
This timestamp causes issues for the "Reproducible Builds" project[1-2].
In Debian, it is then recommended to disable this timestamp by default.
Because these packages are linked to a tagged version, the timestamp is
not an important info to keep.
I'm sharing this patch just in case you think it makes sense to disable
it by default. If not, I can maintain this patch just for Debian.
[1] https://reproducible-builds.org/
[2] https://wiki.debian.org/ReproducibleBuilds/TimestampsInDocumentationGeneratedByDoxygen
> doxygen: disable HTML_TIMESTAMP

- configure.ac
- m4/mptcpd_kernel.m4
Detect a MPTCP capable kernel through the "enabled" file in
`/proc/sys/net/mptcp' rather than the <linux/mptcp.h> header alone if
the user hasn't chosen a specific MPTCP kernel, i.e. "upstream" or
"multipath-tcp.org".  This allows mptcpd to be configured for the
multipath-tcp.org kernel by default if that kernel is at detected at
configure-time rather than always falling back on the upstream
kernel.
Previously, the `configure' script would by default fallback on the
upstream kernel support instead of the multipath-tcp.org kernel when
run on a distro using the latter.
> configure: Improve MPTCP kernel detection.

- include/mptcpd/network_monitor.h
- lib/network_monitor.c
- tests/test-network-monitor.c
Add a new `mptcpd_nm_monitor_loopback()` function that allows the user to enable monitoring of loopback network interfaces.  Monitoring of loopback network interfaces is meant primarily for testing purposes.  Mptcpd will retain the previous behavior of only monitoring non-loopback network interfaces by default.
Fixes #208.
> Allow loopback network interface monitoring.

- include/linux/mptcp_org.h
The license is written just below and clearly mention:
GNU General Public License (...) either version 2 of the License,
*or (at your option) any later version*.
This is the GPL-2.0+, not GPL-2.0.
This is sync with upstream (mptcp.org), see:
commit d8f3b283b485 ("mptcp: uapi: fix SPDX License comment")
Reported-by: Thorsten Alteholz <debian@alteholz.de>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
> mptcp: uapi: fix SPDX License comment

- src/commands.h
Declare inline functions with the static storage class to address
"undefined reference" link-time errors that occur when building mptcpd
with gcc-12.
Co-authored-by: Mat Martineau <mathew.j.martineau@linux.intel.com>
> src: Fix gcc 12 link error.

- tests/test-network-monitor.c
Make sure NULL mptcpd network monitoring operations are handled
gracefully during operation registration.
> tests: Verify proper handling of NULL NM ops.

- lib/id_manager.c
- lib/network_monitor.c
- lib/path_manager.c
- lib/plugin.c
- plugins/path_managers/addr_adv.c
- plugins/path_managers/sspi.c
- src/commands.c
- src/configuration.c
- src/mptcpd.c
- src/netlink_pm.c
- src/netlink_pm_upstream.c
- src/path_manager.c
- tests/plugins/noop/noop.c
- tests/plugins/priority/one.c
- tests/plugins/priority/two.c
- tests/plugins/security/four.c
- tests/plugins/security/three.c
- tests/test-commands.c
- tests/test-configuration.c
- tests/test-network-monitor.c
- tests/test-path-manager.c
ELL 0.45 and later have header files that use a trailing semicolon with
the DEFINE_CLEANUP_FUNC() macro, which is not compatible with the
"-pedantic" flag in gcc. This causes the mptcpd code to issue the
following error:
"ISO C does not allow extra ‘;’ outside of a function [-Werror=pedantic]"
Wrap the ELL includes in some pragmas to avoid this error.
> Fix compatibility with ELL 0.45 and later

- tests/test-sockaddr.c
The following compile-time error occurs in tests/test-sockaddr.c when
building mptcpd with clang 14:
error: initializer element is not a compile-time constant
Drop the "static" storage qualifier as needed to address this error.
> tests: Fix clang initialization error.

- AUTHORS
- NEWS
- configure.ac
- Inconsistent byte order handling in mptcpd was corrected.  IP ports
sent in path management commands and events now have the correct
byte order.  Furthermore, the mptcpd unit test suite no longer
assumes that the tests will be run on a little endian host.  IPv4
addresses and IP ports used in the mptcpd unit test suite are now
byte swapped as needed according to the endianness of the platform.
As always, IPv4 addresses and IP ports passed through pointers to
struct sockaddr should be in network byte order by convention.
- A potential memory violation caused when attempting to register NULL
networking monitoring operations with mptcpd was fixed.
- Mptcpd now supports gcc 12.  Link-time errors found in gcc 12 mptcpd
builds were fixed.
- ELL 0.45 or greater is supported.
- Code coverage was …
> mptcpd 0.10

- src/configuration.c
The section of merge_config() that copies entries from one
plugins_to_load queue to another was copying string pointers from one to
the other. When the source queue was freed, the string pointers in the
destination queue became invalid.
This manifested as garbage strings for the plugins_to_load value if the
load-plugins line was used in mptcpd.conf
To fix, populate the destination queue entries with l_strdup()'d
strings.
> configuration: Fix use-after-free in merged configuration for load-plugins

- lib/network_monitor.c
Make the mptcpd network monitor IPv4 and IPv6 "test net" addresses used for default route checks `static` constants to make sure they are initialized at compile-time instead of run-time.
The `MPTCPD_CONSTANT_HTONL()` macro was used to allow the test IPv4 address to be initialized at compile-time.  This also change also removes the re-initialization of the IPv4 test net address each time mptcpd network monitor operations are registered.
Pre-change object file size (-O2 optimization):
```
text    data     bss     dec     hex filename
10045     232       4   10281    2829 libmptcpd_la-network_monitor.o
```
Post-change object file size (-O2 optimization):
```
text    data     bss     dec     hex filename
10060     216       0   10276    2824 libmptcpd_la-network_monitor.o
```
> network_monitor: Make test addrs static constants.

- src/configuration.c
Fix memory leaks that occured when parsing the "`addr-flags`" and
"`notify-flags`" entries in the mptcpd configuration file.  The string
returned from the ELL `l_settings_get_string()` function is dynamically
allocated and must be deallocated with `l_free()`.
Reported-by: Mat Martineau <mathew.j.martineau@linux.intel.com>
> configuration: Fix addr/notify flag string leaks.

- tests/test-network-monitor.c
This test currently fails if it detects an active interface without any
IPv4 or v6 addresses.
This situation is valid, e.g. when an interface is attached to a bridge.
This bridge would have attached IP addresses but not the interface.
Fixes: c7e2201 ("mptcpd 0.1a: Initial alpha release.")
Reported-by: Adam Borowski
Signed-off-by: Matthieu Baerts
> tests: net-mon: do not fail when iface has no addr

- include/mptcpd/Makefile.am
- include/mptcpd/network_monitor.h
- include/mptcpd/private/network_monitor.h
- include/mptcpd/types.h
- lib/network_monitor.c
- src/configuration.c
- src/path_manager.c
- tests/test-cxx-build.cpp
- tests/test-network-monitor.c
Move `mptcpd_nm_create()`,  `mptcpd_nm_destroy()`, and related notify
flags to a new `<mptcpd/private/network_monitor.h>` header.  They are
only meant for internal mptcpd use.
> Mark network monitor factory functions as private.

- src/netlink_pm_upstream.c
Implement `mptcpd_pm_set_backup()` for upstream kernel.
Closes #237.
> Implement set_backup() for upstream kernel.

- NEWS
- configure.ac
- man/mptcpd.8.in
- Support for the user space MPTCP path management generic netlink API in the upstream Linux 5.19 kernel was implemented.
- MPTCP address advertisements may now be managed through the `mptcpd_pm_add_addr()` and `mptcpd_pm_remove_addr()` functions.  Listening sockets required for accepting subflow joins through advertised addresses will be handled automatically by mptcpd if not previously created through the mptcpd listener manager API described below.
- The `mptcpd_pm_add_addr()` `struct sockaddr` parameter is now non-`const` to allow a zero valued TCP port to be updated with the ephemeral port chosen by the kernel and passed back to the user through that `struct sockaddr` parameter.
- Subflows may be managed through mptcpd plugins through the `mptcpd_pm_add_subflow()`, …
> mptcpd 0.11

- lib/network_monitor.c
Correct a potential NULL pointer dereference when cleaning up resources in the case of a failed attempt to track a network address.
Fixes #230.
> network_monitor: Fix potential NULL dereference.

- include/mptcpd/path_manager.h
- src/netlink_pm_upstream.c
The `MPTCP_PM_ADDR_FLAG_SIGNAL` flag is required when a port is specified.  Make sure it is set when setting flags for the given network address through through `mptcpd_kpm_set_limits()`.
This also corrects an invalid argument (`EINVAL`) error exhibited by the `test-commands` unit test.
> src: Set MPTCP_PM_ADDR_FLAG_SIGNAL as needed.

- tests/test-commands.c
The `test-commands` unit test fails due to a number of issues:
* It incorrectly assumes the `add_addr_accepted` and `subflows` (see [ip-mptcp(8)](https://man7.org/linux/man-pages/man8/ip-mptcp.8.html)) MPTCP resource limits are zero at test start, which causes the `get_limits` command test case to fail when either one of those MPTCP limits is non-zero.
* The `set_flags` command test case was performed after the `remove_addr`  test case.  This caused the kernel to return an invalid argument (`EINVAL`) error since the network address for which flags were to be set was no longer tracked by the kernel.
* The main event loop exited before all of the underlying generic netlink send and receive operations were completed, which then prevented the mptcpd command test cases from completing …
> Correct test-commands unit test failures.

- src/netlink_pm_upstream.c
Correct generic netlink command payload buffer size calculations by aligning against the size of the attribute (e.g. `sizeof(uint16_t)`) as  expected instead of size of the attribute size (e.g. `sizeof(sizeof(uint16_t))`).
Payload buffer sizes should now be smaller in some cases since netlink attributes are aligned on a 4 byte boundary.  For example, the underlying `NLA_ALIGN()` macro returns `4` when the type is `uint16_t`, i.e. `NLA_ALIGN(sizeof(uint16_t))`.  Previously, `8` was returned on 64 bit platforms since the `NLA_ALIGN()` call was incorrectly called as `NLA_ALIGN(sizeof(sizeof(uint16_t)))`, which boils downs to `NLA_ALIGN(size_t)`.
> src: Fix genl command payload size calculations.

- src/netlink_pm_upstream.c
When adding a new subflow send the user supplied remote address ID generic netlink attribute along with the command rather than ignoring it.  The upstream kernel currently doesn't parse the remote address ID, but it may do so in the future.
> src: Send remote address ID on subflow creation.

- tests/Makefile.am
- tests/test-listener-manager.c
The mptcpd listener manager will fail with a "_Protocol not supported_"  error when run against Linux kernels that do not support MPTCP.  Skip the test rather than fail with an error if MPTCP support isn't available.
Fixes #271.
> tests: Skip listener manager test if no MPTCP.

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- configure.ac
- mptcpd.dox
A set of changes made in preparation for the move of `intel/mptcpd` repository to `multipath-tcp/mptcpd`.
> Prepare for move to multipath-tcp/mptcpd

- include/linux/mptcp_upstream.h
Update mptcpd's copy of `<linux/mptcp.h>` to the latest version.
> include: Update mptcp_upstream.h

- NEWS
- configure.ac
- mptcpd will be hosted at https://github.com/multipath-tcp/mptcpd
after this release.
- The payload sizes of path management commands sent to the kernel
were reduced in some cases, slightly improving performance.
- Automatically set the "`signal`" flag when a TCP/IP address with a
non-zero port is passed to the `mptcpd_kpm_set_flags()` function.  The
"`signal`" flag is required when a port is specified.
- A potential memory violation that occurred when cleaning up
resources in the case of a failed attempt to track a network
address was corrected.
- Several order of operation problems in the `test-commands` unit test
were addressed.  The `test-commands' unit test now succeeds as
expected.
- Skip the listener manager unit test if the kernel doesn't support
MPTCP.
> mptcpd 0.12

- tests/mptcpwrap-tester.c
This file could be missing, which will cause getprotobynumber() to return NULL.
The returned pointer is used to mention the protocol name in a warning message, not critical. Instead, we can simply display 'Unknown' next to the protocol ID.
Fixes: d6a48d4 ("tests: Expand mptcpwrap code coverage. (#169)")
Reported-by: Aurelien Jarno @aurel32
Closes: https://bugs.debian.org/1060285
> tests: fix segfault with no /etc/protocols

- .github/workflows/ccpp.yml
- .github/workflows/ell-master.yml
- .github/workflows/multipath-tcp.org.yml
- README.md
The default branch name is now 'main' (see #289), so the Coveralls badge URLs and Github actions need to reference that branch name.
> Update branch references

- scripts/Makefile.am
- scripts/mptcp-get-debug
This is a simple script that is here to get debug info. It will be helpful to get more details in case of issues with MPTCP in general, not specific to mptcpd or mptcpize then.
The script is basic, supporting `/bin/sh` with a minimum of dependences.
It should be used with `--collect` or `--reproduce`, as shown by the help menu.
Please note that a lot of efforts have been done recently to improve the documentation on mptcp.dev website, on the kernel side, and on IPRoute side. Thanks to that, this script can be small, focussing on this small set of commands for the moment. It can always be improved later on.
The idea is to place it here in mptcpd, to have it somewhere, and ideally already installed on some machines, in `/usr/libexec` dir, ready to be used without having to install it.
cc …
> scripts: get debug info for bug reports

- etc/mptcpd.conf.in
- man/mptcpd.8.in
Hello. This patch improves the check_route address notification flag documentation. I suppose there's a 70 column limit on the files I've modified so I've folllowed that limit. Let me know if the patch subject is not OK.
> Improve check_route address notification flag documentation

- configure.ac
- lib/network_monitor.c
ELL 0.68 introduced a non-backward compatible change to its API by introducing a new `l_netlink_message` API to simplify use of the `l_netlink_send()` function.   Support both the pre- and post- ELL 0.68 versions of the `l_netlink_send()` function.
Fixes #299.
> Support ELL 0.68 l_netlink_message API.

- .github/workflows/ccpp.yml
- .github/workflows/coverage.yml
- .github/workflows/ell-master.yml
- .github/workflows/multipath-tcp.org.yml
We recently had some issues because the ELL API has been broken without notice.
Simply adding a cron to run the tests once a day during the week should tell us when an incompatible change has been introduced on ELL side, so we can get a bit of time to prepare a fix and a new release.
While at it, also switch to newer versions of some deprecated GH actions.
> gh: daily validation of the ELL compatibility

- include/mptcpd/plugin.h
- include/mptcpd/private/plugin.h
- lib/plugin.c
- plugins/path_managers/sspi.c
- src/path_manager.c
- tests/lib/call_count.c
- tests/lib/call_plugin.c
- tests/lib/test-plugin.h
- tests/plugins/noop/noop.c
- tests/plugins/priority/one.c
- tests/plugins/priority/two.c
- tests/plugins/security/four.c
- tests/plugins/security/three.c
- tests/test-plugin.c
These events have been added to the upstream kernel a while ago, see commit [f8c9dfbd875b](https://github.com/torvalds/linux/commit/f8c9dfbd875b1) ("mptcp: add pm listener events") in the kernel.
To better explain why these events are useful, better to quote the [feature request](https://github.com/multipath-tcp/mptcp_net-next/issues/313):
> MPTCP for Linux, when not using the in-kernel PM, depends on the userspace PM to create extra listening sockets before announcing addresses and ports. Let's call these "PM listeners".
>
> With the existing MPTCP netlink events, a userspace PM can create PM listeners at startup time, or in response to an incoming connection. Creating sockets in response to connections is not optimal: ADD_ADDRs can't be sent until the sockets are created and listen()ed, …
> Support listener events

- configure.ac
The API has been modified: only new items have been added, see PR #297 and #304.
It is then required to increase CURRENT and AGE, according to libtool's documentation.
> lib: switch to v4.0.1: only added items

- scripts/mptcp-get-debug
It is important to know which kernel version is being, and the OS can give some clues as well.
> scripts: debug: also print system info

- NEWS
- configure.ac
- mptcpd now supports ELL 0.68.
- Documentation was improved for the "check_route" address
notification flag.
- Listening socket creation is now optional for users space path
manager plugins.  Plugins may now call
mptcpd_pm_add_addr_no_listener() instead of mptcpd_pm_add_addr() to
announce a new address without creating a new listener socket.
- The script `mptcp-get-debug' was added to help simplify information
collection for MPTCP related bug reports in general, not just for
mptcpd alone.  It is installed in the `libexec' directory for a
given Linux distribution, such as `/usr/local/libexec'.  Run it with
the '--help' command line argument to list available options.
- A crash (seg fault) that occured if the `/etc/protocols' file does
not exist was fixed.
> mptcpd 0.13

- README.md
That's the easiest way to install mptcpd.
With a badge listing which versions are available where.
> README: installation from packages repo

- README.md
- mptcpd.dox
Because for someone new, it might not be clear what it does.
The idea is also to modify the welcome page on mptcpd.mptcp.dev with the same description.
Note that I also modified the main [wiki](https://github.com/multipath-tcp/mptcpd/wiki) page with the same description.
> doc: describe the default behaviour

- .github/workflows/coverage.yml
'ubuntu-latest' is now following Ubuntu 24.04, which comes with LCOV 2.0.
That's great, but the autoconf-archive package in Ubuntu 24.04 doesn't support LCOV 2.0, a fix [1] is missing.
The simple solution not to block further development is to switch back to Ubuntu 22.04 for this workflow.
Link: https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=commit;h=fc10ebf6185441fcd5e0c0a183fcb97497553594 [1]
> github: coverage: back to Ubuntu 22.04

- src/mptcpize.c
If any.
Before, previously set `LD_PRELOAD` were overridden. According to '`man ld.so`', there can be more than one library to load before other objects as this env var accepts a list separated by spaces or colons:
> A list of additional, user-specified, ELF shared objects to be loaded before all others.  This feature can be used to selectively override functions in other shared objects.
> 
> The items of the list can be separated by spaces or colons, and there is no support for escaping either separator.
So let's do that: if a previous `LD_PRELOAD` is detected, it will no longer be dropped, but used with the MPTCP Wrap library added at the end, e.g.
LD_PRELOAD=dummy.so:libmptcpwrap.so.0.0.1
cc: @pabeni
> mptcpize: do not override existing LD_PRELOAD value

- src/mptcpize.c
GO apps don't use the libC, so the `LD_PRELOAD` technique doesn't work with these apps.
But since GO 1.21, MPTCP is natively supported, and can be forced by simply setting `GODEBUG=multipathtcp=1`. So `mptcpize` can easily support GO apps by also setting this env var.
Similar to the `LD_PRELOAD` env var, the `GODEBUG` one is appended with a comma if it was already set.
Link: https://go.dev/doc/godebug
Link: https://pkg.go.dev/net#Dialer.SetMultipathTCP
Depends-on: #315
> mptcpize: set `GODEBUG=multipathtcp=1` env var

- .github/workflows/ccpp.yml
- .github/workflows/coverage.yml
- .github/workflows/ell-master.yml
- .github/workflows/ell-min.yml
- .github/workflows/multipath-tcp.org.yml
Instead of compiling the min version all the time. Use a more "normal" setup.
While at it, use `-j`
> github: use ell from repo by default 

- .github/workflows/ccpp.yml
- .github/workflows/ell-master.yml
- .github/workflows/ell-min.yml
Otherwise, only a vague error is printed:
../test-driver: line 112: 18416 Aborted (core dumped) "$@" >> "$log_file" 2>&1
> github: check: print logs in case of errors

- .github/workflows/ccpp.yml
- .github/workflows/coverage.yml
- .github/workflows/ell-master.yml
- .github/workflows/ell-min.yml
Some actions will be restricted to root, check with and without.
That will increase a bit the code coverage (~5%).
> github: also run 'make check' as root

- tests/test-commands.c
ELL 0.72 recently changed the way the subtests are executed: each one is now executed in a dedicated process, forked from the same parent [1].
This is causing issues for the `commands` test, because some shared info are shared between subtests. `info` could be created in a shared memory with `mmap()`, but it looks like there are more changes needed in mptcpd itself to cope with that, probably the memory allocated for the pm structure and more.
Then, for the moment, it looks better and easier to simplify things, an only use one subtest.
While at it, also fix `l_test_init()` used with the wrong `argv` (the one for mptcpd, instead of the one for the test).
Note that the breaking issue has been reported to the ELL ML [2], but this didn't block the 0.72 release :) (cc @mjmartineau)
Link: …
> tests: commands: only use one subtest

- configure.ac
- include/mptcpd/private/sockaddr.h
- scripts/check-permissions
- src/configuration.c
- src/mptcpize.c
Here are a few small patches needed to be able to compile mptcpd with musl, e.g. on AlpineLinux
> musl compat
